<?php

// config/schools.php
// Master list of place-of-assignment options for the searchable dropdown.
//
// Two categories:
//   'schools'    - individual schools (elementary, secondary, integrated).
//                  STARTING list compiled from actual DepEd Cavite Division
//                  Memoranda (Call for Applications attachments). Known to
//                  be incomplete -- does not yet cover every school in the
//                  division. Add new schools by appending a new line.
//   'sdo_units'  - Schools Division Office-level units/sections (not tied
//                  to a specific school), e.g. ICT Unit, SGOD, CID, etc.
//                  STARTING scaffold of common DepEd SDO offices, NOT yet
//                  confirmed against this specific division's actual org
//                  structure -- verify and correct before relying on it.

return [
    'schools' => [
        'Agus-os ES',
        'Alfonso Integrated High School',
        'Amadeo ES',
        'Amadeo Integrated School',
        'Amaya ES',
        'Amaya Sch. of Home Industries',
        'Amuyong Elementary School',
        'Antonio B. del Rosario Sr. Mem. ES',
        'Anuling Lejos Integrated High School',
        'Area J ES',
        'Bagbag National High School',
        'Bailen ES',
        'Banaba Cerca Integrated School',
        'Bancod ES',
        'Bendita Integrated High School',
        'Binakayan National High School',
        'Bucal I ES',
        'Bucal National High School - Sta. Mercedes Annex',
        'Bucal National Integrated School',
        'Buho ES',
        'Bulalo ES',
        'Bulalo ES - Annex',
        'Bulihan Integrated National High School',
        'Bulihan Sites & Services Project ES',
        'Cabangaan ES',
        'Cabulusan ES',
        'Caluangan ES',
        'Caluangan National High School',
        'Calumpang Lejos ES',
        'Carasuchi ES',
        'Carmen ES',
        'Cavite Science Integrated School',
        'Constancio E. Aure Sr. National High School',
        'Dao ES',
        'Emilia Ambalada Poblete Integrated High School',
        'Emiliano T. Tirona Memorial National High School',
        'Feliciano Cabuco ES',
        'Francisco Osorio National High School',
        'Francisco P. Tolentino Integrated High School',
        'Galicia ES',
        'Gen. Emilio Aguinaldo-Bailen Integrated School',
        'Gen. Mariano Alvarez Tech. High School',
        'Guitasin PS',
        'Guyung-Guyong ES',
        'Halang Banaybanay NHS',
        'Harasan ES',
        'Hugo Perez ES',
        'Indang Integrated National High School',
        'Kaingen-Poblacion ES',
        'Kanggahan ES',
        'Kaong ES',
        'Kaong National High School',
        'Kaymisas ES',
        'Kaypaaba ES',
        'Kaytambog ES',
        'Kaytitinga Integrated School',
        'Layong Mabilog ES',
        'Lucsuhin Integrated School',
        'Luis Aguado National High School',
        'Lumampong Balagbag ES',
        'Lumampong INHS',
        'Lumampong Integrated National High School',
        'Lumil Integrated National High School',
        'Lumipa ES',
        'Mahabang Kahoy Lejos ES',
        'Malabag National High School',
        'Malainen Bago Integrated School',
        'Maragondon National High School',
        'Marahan ES',
        'Marcelo D. Samaniego ES (Bucal IV ES)',
        'Mataas Na Burol ES (Burol ES)',
        'Matagbak ES',
        'Medina ES',
        'Mendez-Nuñez National High School',
        'Munting Ilog Integrated National High School',
        'Naic Coastal Integrated National High School',
        'Naic ES',
        'Naic Integrated National High School',
        'Naic Senior High School Stand-Alone',
        'Narvaez ES',
        'Noveleta National High School',
        'Noveleta Senior High School',
        'Pacheco ES',
        'Paligawan ES',
        'Palocpoc ES',
        'Pangil NHS',
        'Pantihan II ES',
        'Petronilo L. Torres MES',
        'Pulo ni Sara ES',
        'Pulo ni Sara Integrated School',
        'Pulong Bunga ES',
        'Pulong Saging ES',
        'Punta ES',
        'Puting Kahoy ES',
        'Ricardo Lejos Cortez ES',
        'Rosa G. Acuña Memorial ES',
        'Rosario National High School',
        'San Miguel ES',
        'Santiago L. Angue, Sr. ES (formerly Mabato ES)',
        'Sicat ES',
        'Silang Central School',
        'Sta. Mercedes ES',
        'Tagaytay City National High School',
        'Tagaytay City Science National High School - Integrated Senior High School',
        'Talipusngo ES',
        'Talon Integrated School',
        'Tambo Balagbag ES',
        'Tanza NTS Annex',
        'Tanza National Comprehensive High School',
        'Tanza National Trade School',
        'Tatiao ES',
        'Taywanak ES',
        'Taywanak National High School',
        'Ternate Integrated National High School',
        'Ternate West National High School',
        'Timalan ES',
        'Timalan Hillsview Integrated School',
        'Trece Martires City National High School',
        'Tua ES',
        'Urdaneta ES',
        'Victoriano Luciano ES',
    ],

    'sdo_units' => [
        'Office of the Schools Division Superintendent (SDS)',
        'Office of the Assistant Schools Division Superintendent (ASDS)',
        'Curriculum Implementation Division (CID)',
        'School Governance and Operations Division (SGOD)',
        'Schools Division ICT Unit',
        'Human Resource Management and Development Unit',
        'Legal Unit',
        'Finance Unit / Accounting Section',
        'Budget Section',
        'Cash Section',
        'Supply/Property Section',
        'Records Section',
        'General Services Unit',
        'Planning and Research Section',
    ],
];
